### ISSUE TITLE
Error 502. Disconnected (reason:transport error).

### ISSUE THREAD

**Issue by AlessandroChecco** [graphistry/pygraphistry#75]
I get this error when trying to plot a graph that is not the one in the tutorial. Any idea?

Debug ID: 7057-C579

**Comment by lmeyerov** [comment]
Hi Alessandro, we were able to reproduce the issue, so will dig in further. Thank you for reporting!

**Comment by lmeyerov** [comment]
Hi @AlessandroChecco  We found the issue: this was hitting an edge case in one of our algorithms for highly non-graph-like datasets. Most of the data in that workload was points with no connections, or edges with no adjacent edges, which an otherwise fast approximate community detection algorithm was not expecting.

For the interim, I recommend simply pre-filtering those from the upload. They should not be too interesting from a graph analysis standpoint to beginwith, so that should hopefully not be an issue. We'll fix this for the next release, however, as we still ought to support this scenario!

**Comment by AlessandroChecco** [comment]
Wow fast response. Thanks a lot, will do!

**Comment by lmeyerov** [comment]
(Reopening until the public server gets the fix)
